SKILLS = [
    "python","java","javascript","c++","c#","sql","pandas","numpy","scipy","matplotlib","seaborn",
    "plotly","jupyter","excel","power bi","tableau","data analysis","data visualization",
    "exploratory data analysis","feature engineering","feature selection","data preprocessing","statistical analysis",
    "hypothesis testing","machine learning","supervised learning","unsupervised learning","regression","classification",
    "clustering","decision trees","random forest","xgboost","lightgbm","logistic regression","linear regression",
    "knn","naive bayes","model evaluation","cross validation","hyperparameter tuning","deep learning","neural networks","cnn",
    "rnn","lstm","gru","transformers","tensorflow","keras","pytorch","natural language processing","text preprocessing",
    "text classification","tokenization","tf-idf","word2vec","bert","sentence transformers","computer vision","opencv",
    "image classification","object detection","yolo","generative ai","llm","rag","prompt engineering","langchain","embeddings",
    "vector databases","agents","fastapi","flask","django","rest api","api development","mysql","postgresql","mongodb",
    "redis","git","github","docker","mlflow","aws","azure","google cloud","support vector machines"
]

SKILL_ALIASES = {
    "sklearn": "scikit-learn",
    "scikit learn": "scikit-learn",
    "scikit_learn": "scikit-learn",
    "nlp": "natural language processing",
    "eda": "exploratory data analysis",
    "rf": "random forest",
    "randomforest": "random forest",
    "xgb": "xgboost",
    "lgbm": "lightgbm",
    "svm": "support vector machines",
    "support vector machine": "support vector machines",
    "ann": "neural networks",
    "neural network": "neural networks",
    "tf": "tensorflow",
    "tf-idf": "tf-idf",
    "tf idf": "tf-idf",
    "tfidf": "tf-idf",
    "word 2 vec": "word2vec",
    "word 2vec": "word2vec",
    "sentence transformer": "sentence transformers",
    "cv": "computer vision",
    "opencv-python": "opencv",
    "yolov8": "yolo",
    "yolov9": "yolo",
    "yolov10": "yolo",
    "yolov11": "yolo",
    "llms": "llm",
    "large language model": "llm",
    "large language models": "llm",
    "genai": "generative ai",
    "gen ai": "generative ai",
    "retrieval augmented generation": "rag",
    "vector database": "vector databases",
    "vector db": "vector databases",
    "ai agents": "agents",
    "agentic ai": "agents",
    "restful api": "rest api",
    "restful apis": "rest api",
    "postgres": "postgresql",
    "postgres sql": "postgresql",
    "amazon web services": "aws",
    "cross-validation": "cross validation",
    "hyperparameter optimization": "hyperparameter tuning",
    "c plus plus": "c++",
    "cpp": "c++",
    "c sharp": "c#",
    "dotnet": ".net",
    "dot net": ".net"
}
